<?php

namespace Database\Seeders\Master;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobTitleSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['JobTitle' => 'Head of Technical I General Reinsurance Division', 'IsActive' => true],
            ['JobTitle' => 'Technical Accounting Officer', 'IsActive' => true],
            ['JobTitle' => 'General Accounting & Tax Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Information Technology Division', 'IsActive' => true],
            ['JobTitle' => 'Senior Marketing Manager', 'IsActive' => true],
            ['JobTitle' => 'Data Analyst & Portfolio Process 1', 'IsActive' => true],
            ['JobTitle' => 'General Reinsurance Operation Support Staff', 'IsActive' => true],
            ['JobTitle' => 'Temporary Staff', 'IsActive' => true],
            ['JobTitle' => 'Underwriter (Fac. Industrial, Engineering Major Risks)', 'IsActive' => true],
            ['JobTitle' => 'Head of Adm. & Portfolio-1 Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Corp. Legal Department', 'IsActive' => true],
            ['JobTitle' => 'Driver', 'IsActive' => true],
            ['JobTitle' => 'General Reinsurance Treaty', 'IsActive' => true],
            ['JobTitle' => 'Vice Director Claim Service & Loss Adjusting', 'IsActive' => true],
            ['JobTitle' => 'Head of Risk Management Department', 'IsActive' => true],
            ['JobTitle' => 'Data Analyst, Process, & Claim Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Treaty Department', 'IsActive' => true],
            ['JobTitle' => 'General Reinsurance Claim Services Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Finance Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Analytics, Retrocession & Outward Department', 'IsActive' => true],
            ['JobTitle' => 'Life Reinsurance Product Development and Statistics Staff', 'IsActive' => true],
            ['JobTitle' => 'Sharia Life Reinsurance Adm. & Claim Staff', 'IsActive' => true],
            ['JobTitle' => 'Staff', 'IsActive' => true],
            ['JobTitle' => 'IT Services Staff', 'IsActive' => true],
            ['JobTitle' => 'Internal Auditor', 'IsActive' => true],
            ['JobTitle' => 'Head of Sharia Reinsurance Unit', 'IsActive' => true],
            ['JobTitle' => 'Head of Human Capital Management Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Operation Support Department', 'IsActive' => true],
            ['JobTitle' => 'Receptionist', 'IsActive' => true],
            ['JobTitle' => 'Head of IT Services Department', 'IsActive' => true],
            ['JobTitle' => 'Developer Officer', 'IsActive' => true],
            ['JobTitle' => 'Claim Analyst', 'IsActive' => true],
            ['JobTitle' => 'Life Reinsurance Underwriting Staff', 'IsActive' => true],
            ['JobTitle' => 'Sharia Accounting Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Investment & Financial Analysis Department', 'IsActive' => true],
            ['JobTitle' => 'Finance Officer/Chasier', 'IsActive' => true],
            ['JobTitle' => 'Collection Officer', 'IsActive' => true],
            ['JobTitle' => 'General Reinsurance Claim Supervisor', 'IsActive' => true],
            ['JobTitle' => 'System Development Staff', 'IsActive' => true],
            ['JobTitle' => 'Facultative Commercial Staff', 'IsActive' => true],
            ['JobTitle' => 'Legal Officer', 'IsActive' => true],
            ['JobTitle' => 'Life Reinsurance Claim Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Marketing Life Reinsurance Division', 'IsActive' => true],
            ['JobTitle' => 'Sharia Accounting Officer', 'IsActive' => true],
            ['JobTitle' => 'Advisor', 'IsActive' => true],
            ['JobTitle' => 'Sharia Life Technical Staff', 'IsActive' => true],
            ['JobTitle' => 'Technical Accounting Staff', 'IsActive' => true],
            ['JobTitle' => 'Deputy Head of Technical  Life Reinsurance Division (Adm. and Claim)', 'IsActive' => true],
            ['JobTitle' => 'Head of Internal Audit', 'IsActive' => true],
            ['JobTitle' => 'Risk Management & Compliance Officer', 'IsActive' => true],
            ['JobTitle' => 'Head of Infrastructure Department', 'IsActive' => true],
            ['JobTitle' => 'Director', 'IsActive' => true],
            ['JobTitle' => 'Adm. & Portfolio 2 Officer', 'IsActive' => true],
            ['JobTitle' => 'Facultative Financial Lines & Marine Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Life Reinsurance Product Development & Statistics Department', 'IsActive' => true],
            ['JobTitle' => 'Operation Support Officer', 'IsActive' => true],
            ['JobTitle' => 'Assistant Corporate Secretary', 'IsActive' => true],
            ['JobTitle' => 'Head of Facultative Industrial, Engineering Major Risks Department', 'IsActive' => true],
            ['JobTitle' => 'Analytics, Retrocession & Outward Supervisor', 'IsActive' => true],
            ['JobTitle' => 'Head of Data Based and Reporting Department', 'IsActive' => true],
            ['JobTitle' => 'Data Analyst & Portfolio Process 2', 'IsActive' => true],
            ['JobTitle' => 'IT Quality Assurance Staff', 'IsActive' => true],
            ['JobTitle' => 'Senior Secretary', 'IsActive' => true],
            ['JobTitle' => 'Deputy Head of Technical II Life Reinsurance Division (Underwriting and Retro)', 'IsActive' => true],
            ['JobTitle' => 'Head of Technical I Life Reinsurance Division', 'IsActive' => true],
            ['JobTitle' => 'Head of General Accounting & Tax Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Technical Accounting & Collection Division', 'IsActive' => true],
            ['JobTitle' => 'Head of Sharia Life Adm. & Claim Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Client Services & Post Acquisition Division', 'IsActive' => true],
            ['JobTitle' => 'Analytics, Retrocession & Outward Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Life Claim Services Department', 'IsActive' => true],
            ['JobTitle' => 'Underwriter', 'IsActive' => true],
            ['JobTitle' => 'Infrastructure Officer', 'IsActive' => true],
            ['JobTitle' => 'Head of Technical Accounting Department', 'IsActive' => true],
            ['JobTitle' => 'Investment Staff', 'IsActive' => true],
            ['JobTitle' => 'Senior Underwriter (Facultative Commercial)', 'IsActive' => true],
            ['JobTitle' => 'President Director', 'IsActive' => true],
            ['JobTitle' => 'Office Boy', 'IsActive' => true],
            ['JobTitle' => 'Data Based and Reporting Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of System Development Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Adm.& Portfolio-2 Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Human Capital & General Affairs Division', 'IsActive' => true],
            ['JobTitle' => 'Head of IT Quality Assurance Department', 'IsActive' => true],
            ['JobTitle' => 'Analyst Product & Actuary', 'IsActive' => true],
            ['JobTitle' => 'Head of Claim Services Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Human Capital Operational & GA Department', 'IsActive' => true],
            ['JobTitle' => 'Risk Management & Survey Staff', 'IsActive' => true],
            ['JobTitle' => 'Training Officer', 'IsActive' => true],
            ['JobTitle' => 'Business Analyst and Strategic Development Staff', 'IsActive' => true],
            ['JobTitle' => 'Head of Sharia Life Technical Department', 'IsActive' => true],
            ['JobTitle' => 'General Affair Officer', 'IsActive' => true],
            ['JobTitle' => 'IT Services Officer', 'IsActive' => true],
            ['JobTitle' => 'Senior Underwriter (Facultative Financial Lines & Marine)', 'IsActive' => true],
            ['JobTitle' => 'Head of Facultative General Division', 'IsActive' => true],
            ['JobTitle' => 'Senior Underwriter (Fac. Industrial, Engineering Major Risks)', 'IsActive' => true],
            ['JobTitle' => 'Head of Collection Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Retro Department', 'IsActive' => true],
            ['JobTitle' => 'Head of Facultative Financial Lines & Marine Department', 'IsActive' => true],
        ];

        foreach ($rows as $row) {
            DB::table('ms_job_title')->updateOrInsert(
                ['JobTitle' => $row['JobTitle']],
                [
                    'IsActive' => $row['IsActive'],
                    'InputUser' => 'Admin',
                    'InputDate' => now(),
                    'ModifUser' => 'Admin',
                    'ModifDate' => now(),
                    'DeletedBy' => null,
                    'DeletedDate' => null,
                ]
            );
        }
    }
}
