@extends('layouts.app')
@section('content')
<div class="container-fluid"><div class="mb-4"><h4 class="mb-1">Employee Equipment Request</h4><div class="text-muted">Update Employee Equipment Request</div></div><x-alert />
<form method="POST" action="{{ route('employee-equipment.update',$equipment->EmpEquipID) }}">@csrf @method('PUT')
<div class="card shadow-sm mb-3"><div class="card-header bg-white"><strong>FORM : EMPLOYEE EQUIPMENT</strong></div><div class="card-body"><div class="row">
<div class="col-md-6 mb-3"><label class="form-label">Emp Equipment ID</label><input class="form-control readonly-field" value="{{ $equipment->EmpEquipID }}" readonly></div><div class="col-md-6 mb-3"><label class="form-label">Emp Form ID</label><input class="form-control readonly-field" value="{{ $equipment->EmpFormID }}" readonly></div><div class="col-md-6 mb-3"><label class="form-label">Req User</label><input class="form-control readonly-field" value="{{ $equipment->ReqUser }}" readonly></div><div class="col-md-6 mb-3"><label class="form-label">Req Date</label><input class="form-control readonly-field" value="{{ $equipment->ReqDate?->format('d - m - Y')??'-' }}" readonly></div>
<div class="col-md-6 mb-3"><label class="form-label">Request Type <span class="text-danger">*</span></label><select name="ReqType" id="ReqType" class="form-select"><option value="Permanent" @selected(old('ReqType',$equipment->ReqType)==='Permanent')>Permanent</option><option value="Temporary" @selected(old('ReqType',$equipment->ReqType)==='Temporary')>Temporary</option></select></div><div class="col-md-6 mb-3"><label class="form-label">Date From <span class="text-danger">*</span></label><input type="date" name="DateFrom" class="form-control" value="{{ old('DateFrom',$equipment->DateFrom?->format('Y-m-d')) }}" required></div><div class="col-md-6 mb-3"><label class="form-label">Date Until <span class="text-danger">*</span></label><input type="date" name="DateUntil" id="DateUntil" class="form-control" value="{{ old('DateUntil',$equipment->DateUntil?->format('Y-m-d')) }}" required></div><div class="col-md-12 mb-3"><label class="form-label">Purpose <span class="text-danger">*</span></label><textarea name="Purpose" rows="3" class="form-control" required>{{ old('Purpose',$equipment->Purpose) }}</textarea></div>
</div></div></div>
<div class="card shadow-sm"><div class="card-header bg-white"><strong>Asset</strong></div><div class="card-body"><div class="row align-items-end mb-3"><div class="col-md-5"><label class="form-label">Asset Type</label><select id="AssetTypeID" class="form-select"><option value="">-- Select Asset Type --</option>@foreach($assetTypes as $type)<option value="{{ $type->AssTypeID }}" @selected((string)$assetTypeId===(string)$type->AssTypeID)>{{ $type->AssetType }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Search Asset</label><input id="assetSearch" class="form-control" value="{{ $assetSearch }}" placeholder="Asset ID, brand, model, serial..."></div><div class="col-md-2"><button type="button" id="reloadAsset" class="btn btn-outline-primary w-100">Reload Asset</button></div></div>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th class="text-center">Select</th><th>Asset ID</th><th>Asset Type</th><th>Brand</th><th>Model</th><th>Serial No</th><th>Description</th></tr></thead><tbody>@forelse($assets as $asset)<tr><td class="text-center"><input type="radio" name="AssetID" value="{{ $asset->AssetID }}" class="form-check-input" @checked(old('AssetID',$equipment->AssetID)===$asset->AssetID)></td><td>{{ $asset->AssetID }}</td><td>{{ $asset->assetType?->AssetType??'-' }}</td><td>{{ $asset->Brand }}</td><td>{{ $asset->Model }}</td><td>{{ $asset->SerialNo }}</td><td>{{ $asset->AssetDesc }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Tidak ada asset aktif untuk Asset Type yang dipilih.</td></tr>@endforelse</tbody></table></div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('employee-equipment.index') }}" class="btn btn-secondary">Cancel</a><button type="submit" class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Update</button></div></div></div></form></div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',function(){const t=document.getElementById('ReqType'),u=document.getElementById('DateUntil');function sync(){u.readOnly=t.value==='Permanent';if(t.value==='Permanent')u.value='1900-01-01';else if(u.value==='1900-01-01')u.value=''}t.onchange=sync;sync();document.getElementById('reloadAsset').onclick=()=>{const type=document.getElementById('AssetTypeID').value;if(!type){alert('Silakan pilih Asset Type terlebih dahulu.');return}const url=new URL(window.location.href);url.search='';url.searchParams.set('AssetTypeID',type);const s=document.getElementById('assetSearch').value.trim();if(s)url.searchParams.set('asset_search',s);location.href=url}});</script>@endpush
@endsection
