@extends('layouts.app')
@section('content')
<div class="container-fluid">
<div class="mb-4"><h4 class="mb-1">Employee Equipment Request</h4><div class="text-muted">Employee Equipment Request List</div></div>
<x-alert />
<div class="card shadow-sm"><div class="card-body">
<form method="GET" action="{{ route('employee-equipment.index') }}" class="mb-3"><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input type="text" name="search" value="{{ $search }}" class="form-control" placeholder="Search anything...">@if($search!=='')<a href="{{ route('employee-equipment.index') }}" class="btn btn-outline-secondary">Clear</a>@endif</div></form>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="text-center" style="width:55px;">#</th><th>Emp Equipment ID</th><th>Emp Form ID</th><th>Asset ID</th><th>Asset Type</th><th>Brand / Model</th><th>Request Type</th><th>Date From</th><th>Date Until</th><th>Status</th></tr></thead><tbody>
@forelse($employeeEquipments as $item)
<tr class="employee-equipment-row" data-id="{{ $item->EmpEquipID }}" style="cursor:pointer"><td class="text-center row-selector"><i class="bi bi-circle-fill text-secondary"></i></td><td>{{ $item->EmpEquipID }}</td><td>{{ $item->EmpFormID }}<small class="d-block text-muted">{{ trim(($item->empForm?->FirstName??'').' '.($item->empForm?->LastName??'')) }}</small></td><td>{{ $item->AssetID }}</td><td>{{ $item->asset?->assetType?->AssetType??'-' }}</td><td>{{ $item->asset?->Brand??'-' }}<small class="d-block text-muted">{{ $item->asset?->Model??'-' }}</small></td><td>{{ $item->ReqType }}</td><td>{{ $item->DateFrom?->format('d M Y')??'-' }}</td><td>{{ $item->DateUntil && $item->DateUntil->format('Y-m-d')!=='1900-01-01'?$item->DateUntil->format('d M Y'):'-' }}</td><td><span class="badge bg-{{ $item->Status==='APPROVED'?'success':($item->Status==='REJECTED'?'danger':($item->Status==='PROGRESS'?'warning text-dark':'secondary')) }}">{{ $item->Status?:'DRAFT' }}</span></td></tr>
@empty<tr><td colspan="10" class="text-center text-muted py-5"><i class="bi bi-inbox fs-3 d-block mb-2"></i>No Employee Equipment Request found.</td></tr>@endforelse
</tbody></table></div>
@if($employeeEquipments->hasPages())<div class="mt-3">{{ $employeeEquipments->links() }}</div>@endif
</div></div>
<div class="d-flex justify-content-end gap-2 mt-3"><a href="{{ route('employee-equipment.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Create</a><button type="button" id="btnUpdate" class="btn btn-warning" disabled><i class="bi bi-pencil me-1"></i>Update</button><button type="button" id="btnDelete" class="btn btn-danger" disabled><i class="bi bi-trash me-1"></i>Delete</button></div>
</div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',function(){let id=null;const rows=document.querySelectorAll('.employee-equipment-row'),u=document.getElementById('btnUpdate'),d=document.getElementById('btnDelete');rows.forEach(r=>r.addEventListener('click',function(){rows.forEach(x=>{x.classList.remove('table-primary');const i=x.querySelector('.row-selector i');if(i)i.className='bi bi-circle-fill text-secondary'});this.classList.add('table-primary');const i=this.querySelector('.row-selector i');if(i)i.className='bi bi-check-circle-fill text-primary';id=this.dataset.id;u.disabled=false;d.disabled=false}));u.onclick=()=>{if(id)location.href="{{ url('/employee-equipment') }}/"+id+'/edit'};d.onclick=()=>{if(!id||!confirm('Are you sure you want to delete this Employee Equipment Request?'))return;const f=document.createElement('form');f.method='POST';f.action="{{ url('/employee-equipment') }}/"+id;f.innerHTML='<input type="hidden" name="_token" value="{{ csrf_token() }}"><input type="hidden" name="_method" value="DELETE">';document.body.appendChild(f);f.submit()};});</script>@endpush
@endsection
